version: "3"

services:
  note-app:
    image: node
    build: .
    ports:
      - "4000:4000"
    links:
      - mongo
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_DB=notesdb
      - PORT=4000
  mongo:
    container_name: database
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
